services:
    celery-worker:
        build: .
        container_name: atlas-worker
        restart: unless-stopped
        command: celery -A celery_app worker --loglevel=info
        env_file:
            - .env
            - .env.docker
        volumes:
            - ./logs:/app/logs
            - ./artifacts:/app/artifacts
        networks:
            - shared-infra

    celery-beat:
        build: .
        container_name: atlas-beat
        restart: unless-stopped
        command: celery -A celery_app beat --loglevel=info
        env_file:
            - .env
            - .env.docker
        volumes:
            - ./logs:/app/logs
            - ./artifacts:/app/artifacts
        networks:
            - shared-infra

networks:
    shared-infra:
        external: true
        name: shared-infra
