"""init_security_model

Revision ID: f71ffc2dc13e
Revises: 
Create Date: 2026-04-26 08:42:50.221834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71ffc2dc13e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=False),
    sa.Column('broker_token', sa.String(length=64), nullable=False),
    sa.Column('exchange_token', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('macro_economic_sector', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('basic_industry', sa.String(length=128), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_ticker'), 'securities', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_ticker'), table_name='securities')
    op.drop_table('securities')
    # ### end Alembic commands ###
