"""make_take_profit_price_nullable

Revision ID: 5f94dbe3d878
Revises: 20260502_feat_tech
Create Date: 2026-05-02 14:19:43.436828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f94dbe3d878'
down_revision = '20260502_feat_tech'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backtest_positions', 'take_profit_price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backtest_positions', 'take_profit_price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    # ### end Alembic commands ###
