"""add_exit_evaluator_class_to_strategy_version

Revision ID: 11e117c627f6
Revises: 2523f762d5ee
Create Date: 2026-06-25 22:17:37.511243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e117c627f6'
down_revision = '2523f762d5ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_versions', sa.Column('exit_evaluator_class', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_versions', 'exit_evaluator_class')
    # ### end Alembic commands ###