"""add_trade_management_tables

Revision ID: 2523f762d5ee
Revises: 80c2fa614676
Create Date: 2026-06-25 07:38:59.777167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2523f762d5ee'
down_revision = '80c2fa614676'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_signal_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_version_id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fill_quantity', sa.Integer(), nullable=True),
    sa.Column('kite_entry_order_id', sa.String(length=100), nullable=True),
    sa.Column('kite_gtt_id', sa.String(length=100), nullable=True),
    sa.Column('timeout_date', sa.Date(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='tradestatus'), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('exit_reason', sa.Enum('ATR_STOP', 'TIMEOUT', 'MANUAL', name='exitreason'), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['strategy_signal_id'], ['strategy_signals.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_security_id'), 'trades', ['security_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_signal_id'), 'trades', ['strategy_signal_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_version_id'), 'trades', ['strategy_version_id'], unique=False)
    op.create_table('trade_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('mtm_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('days_held', sa.Integer(), nullable=False),
    sa.Column('exit_triggered', sa.Boolean(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'snapshot_date', name='uix_trade_snapshot_date')
    )
    op.create_index(op.f('ix_trade_snapshots_trade_id'), 'trade_snapshots', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_snapshots_trade_id'), table_name='trade_snapshots')
    op.drop_table('trade_snapshots')
    op.drop_index(op.f('ix_trades_strategy_version_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_signal_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_security_id'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###