"""Initial Setup

Revision ID: 6d5e3b769e8e
Revises: 
Create Date: 2026-06-14 13:27:23.950813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5e3b769e8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('broker_token', sa.String(length=255), nullable=False),
    sa.Column('exchange_token', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('macro_economic_sector', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('basic_industry', sa.String(length=255), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('ohlcv',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('candle_timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('is_continuous', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'candle_timestamp', 'timeframe', name='uix_security_timestamp_timeframe')
    )
    op.create_index('idx_security_timeframe_timestamp', 'ohlcv', ['security_id', 'timeframe', 'candle_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_security_timeframe_timestamp', table_name='ohlcv')
    op.drop_table('ohlcv')
    op.drop_table('securities')
    # ### end Alembic commands ###