"""Added feature tables

Revision ID: a51782ee9d4b
Revises: 8ef56c37fd60
Create Date: 2026-06-18 08:46:48.783880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51782ee9d4b'
down_revision = '8ef56c37fd60'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('candle_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('advance_decline_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('market_breadth_ema20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('market_breadth_ema50', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pct_above_ema20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pct_above_ema50', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pct_above_ema200', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('new_highs_count', sa.Integer(), nullable=True),
    sa.Column('new_lows_count', sa.Integer(), nullable=True),
    sa.Column('regime_score', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timeframe', 'candle_timestamp', name='uix_market_feature')
    )
    op.create_index('idx_market_feature', 'market_features', ['timeframe', 'candle_timestamp'], unique=False)
    op.create_table('sector_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sector_name', sa.String(length=255), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('candle_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sector_ret_5', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sector_ret_10', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sector_ret_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sector_ret_60', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sector_rs_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sector_rs_60', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_name', 'timeframe', 'candle_timestamp', name='uix_sector_feature')
    )
    op.create_index('idx_sector_feature', 'sector_features', ['sector_name', 'timeframe', 'candle_timestamp'], unique=False)
    op.create_table('security_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ohlcv_id', sa.BigInteger(), nullable=False),
    sa.Column('ema_5', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema_10', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema_50', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema_100', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('dist_ema_5', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('dist_ema_10', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('dist_ema_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('dist_ema_50', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema20_slope_5', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema50_slope_5', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema_compression', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('golden_cross', sa.Boolean(), nullable=True),
    sa.Column('dist_252d_low', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('dist_252d_high', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ema_alignment_score', sa.Integer(), nullable=True),
    sa.Column('days_above_ema20', sa.Integer(), nullable=True),
    sa.Column('trend_efficiency', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ret_5', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ret_10', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ret_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ret_60', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('momentum_acceleration', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('atr_pct', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volatility_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('bb_width', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volatility_contraction', sa.Boolean(), nullable=True),
    sa.Column('atr_expansion', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('gap_frequency_20', sa.Integer(), nullable=True),
    sa.Column('avg_gap_size_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('vol_ma_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('turnover_acceleration', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('avg_turnover_20', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('obv', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('volume_acceleration', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volume_trend', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('up_volume_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('position_in_range', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('near_breakout', sa.Boolean(), nullable=True),
    sa.Column('base_tightness', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('base_width', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('base_duration', sa.Integer(), nullable=True),
    sa.Column('compression_duration', sa.Integer(), nullable=True),
    sa.Column('volatility_contraction_count', sa.Integer(), nullable=True),
    sa.Column('up_days_10', sa.Integer(), nullable=True),
    sa.Column('up_days_20', sa.Integer(), nullable=True),
    sa.Column('strong_close_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('bullish_range_expansion', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('close_near_high', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rs_5', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rs_10', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rs_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rs_60', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rs_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rs_ratio_ret_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rs_ratio_ret_60', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('dist_20d_high', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('dist_50d_high', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('new_20d_high', sa.Boolean(), nullable=True),
    sa.Column('new_50d_high', sa.Boolean(), nullable=True),
    sa.Column('new_252d_high', sa.Boolean(), nullable=True),
    sa.Column('breakout_strength_20', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('breakout_strength_50', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('breakout_volume_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ohlcv_id'], ['ohlcv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ohlcv_id', name='uix_security_feature_ohlcv')
    )
    op.create_index('idx_security_feature_ohlcv', 'security_features', ['ohlcv_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_security_feature_ohlcv', table_name='security_features')
    op.drop_table('security_features')
    op.drop_index('idx_sector_feature', table_name='sector_features')
    op.drop_table('sector_features')
    op.drop_index('idx_market_feature', table_name='market_features')
    op.drop_table('market_features')
    # ### end Alembic commands ###