# backend/app/enums/job.py

from enum import Enum as PythonEnum


class JobType(PythonEnum):
    """Enum for different types of background jobs."""
    KITE_TOKEN_REFRESH = "KITE_TOKEN_REFRESH"
    SECURITIES_IMPORT = "SECURITIES_IMPORT"
    SECURITIES_ENRICHMENT = "SECURITIES_ENRICHMENT"
    OHLCV_IMPORT = "OHLCV_IMPORT"
    FEATURE_GENERATION = "FEATURE_GENERATION"
    STRATEGY_EXECUTION = "STRATEGY_EXECUTION"
    TRADE_ENTRY = "TRADE_ENTRY"
    TRADE_EXIT = "TRADE_EXIT"
    TRADE_RECONCILIATION = "TRADE_RECONCILIATION"
    POSITION_SYNC = "POSITION_SYNC"
    DAILY_ACCOUNT_SNAPSHOT = "DAILY_ACCOUNT_SNAPSHOT"
